name: ci-cd

on:
  push

permissions:
  contents: read

jobs:
  run-app:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install SSH client
        run: sudo apt-get install -y sshpass
      - name: upload app
        run: |
          sshpass -p 'Password123!' ssh -o StrictHostKeyChecking=no azureuser@20.185.67.127 "rm -r orientation-haproxy && git clone https://github.com/shaniblau/orientation-haproxy.git && cd orientation-haproxy && pip install -r requirements.txt"